name: Go Push Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: bash build.bash
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.0
      with:
        # Artifact name
        name: autoupdater
        # A file, directory or wildcard pattern that describes what to upload
        path: out
        # The desired behavior if no files are found using the provided path.